run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - misspell
    - unconvert
    - gofmt

linters-settings:
  gofmt:
    simplify: true
  staticcheck:
    checks: ["all"]

issues:
  exclude-dirs:
    - bin
    - dist
