package cli

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"

	"github.com/markgustetic/sentra/internal/blobstore"
	"github.com/markgustetic/sentra/internal/config"
	"github.com/markgustetic/sentra/internal/repo"
	"github.com/markgustetic/sentra/internal/ui"
)

// InitDeps wires the side-effecting pieces of `sentra init` so tests
// can drop in a memory store and a deterministic passphrase. The
// command itself just walks the lifecycle: load config (or defaults),
// open the store, call repo.Init, write sentra.yaml.
type InitDeps struct {
	// NewStore opens the blobstore the new repo will live in.
	// Production wires this to the S3 store; tests pass an in-memory
	// store. The cfg argument is the merged Config from sentra.yaml +
	// env overlay; for `init` on a fresh dir it's typically Defaults().
	NewStore func(ctx context.Context, cfg *config.Config) (blobstore.Store, error)

	// Passphrase returns the passphrase bytes the new repo will be
	// keyed against. Production typically wires this to
	// ui.PromptPassphraseWithConfirm; tests inject a static value so
	// the run is deterministic.
	Passphrase func() ([]byte, error)

	// Stdout receives the success summary. cobra.Command.SetOut also
	// goes here so callers can wire both in one place; if you set
	// SetOut on the returned command directly, that takes precedence.
	Stdout io.Writer
}

// configFileName is the canonical local config file. Always relative
// to the user's working directory — the design doc is explicit that
// init never reaches outside cwd.
const configFileName = "sentra.yaml"

// initFlags holds the values of the S3 backend flags exposed by
// `sentra init`. Bundled into a struct so the cobra wiring stays
// compact and tests can construct them directly.
type initFlags struct {
	bucket      string
	prefix      string
	region      string
	profile     string
	endpointURL string
}

// renderConfigYAML produces the on-disk sentra.yaml body that init
// writes after a successful repo bootstrap. We render from the
// resolved Config (defaults + yaml + env overlay + flags) so the
// file faithfully reflects what the user actually configured.
//
// The body is hand-shaped rather than yaml.Marshal'd so we can
// keep the inline comments that explain each field — the file is a
// teaching artifact, not just a serialization.
func renderConfigYAML(cfg *config.Config) string {
	return fmt.Sprintf(`# sentra.yaml — repository configuration
# Generated by `+"`sentra init`"+`. Edit and re-run sentra commands; nothing else
# in this file is required to be present.

repo:
  s3:
    bucket: %q              # required for non-local storage
    prefix: %q              # optional; useful when sharing a bucket
    region: %q              # AWS region; e.g. us-west-2
    profile: %q             # AWS shared-config profile, optional
    endpoint_url: %q        # MinIO/LocalStack support; empty for AWS

agent:
  provider: anthropic
  model: claude-sonnet-4-6
  max_findings_to_llm: %d

backup:
  ignore_file: %q
  exclude_caches: %t

retention:
  keep_last: %d
  keep_daily: %d
  keep_weekly: %d
  keep_monthly: %d
`,
		cfg.Repo.S3.Bucket,
		cfg.Repo.S3.Prefix,
		cfg.Repo.S3.Region,
		cfg.Repo.S3.Profile,
		cfg.Repo.S3.EndpointURL,
		cfg.Agent.MaxFindingsToLLM,
		cfg.Backup.IgnoreFile,
		cfg.Backup.ExcludeCaches,
		cfg.Retention.KeepLast,
		cfg.Retention.KeepDaily,
		cfg.Retention.KeepWeekly,
		cfg.Retention.KeepMonthly,
	)
}

// NewInit returns the cobra command for `sentra init`. The command
// validates the destination, opens the configured store via deps,
// calls repo.Init, and writes sentra.yaml. --force allows clobbering
// an existing sentra.yaml; that's required when the user has changed
// passphrase / bucket / region after the fact and is fine with the
// store being re-bootstrapped (typically against a fresh prefix).
//
// Flags:
//   - --force         overwrite an existing sentra.yaml + re-bootstrap repo
//   - --bucket        S3 bucket (required if no sentra.yaml exists yet)
//   - --region        AWS region; e.g. us-west-2
//   - --profile       AWS shared-config profile
//   - --endpoint-url  MinIO/LocalStack base URL; empty for AWS
//   - --prefix        optional key prefix inside the bucket
//
// The flags layer on top of any existing sentra.yaml + env overlays so
// `sentra init --force --bucket new` preserves region/profile from the
// previous file unless those flags are also passed.
func NewInit(deps InitDeps) *cobra.Command {
	var force bool
	flags := &initFlags{}
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize a sentra repository (writes sentra.yaml + repo config)",
		Long: "Create a sentra.yaml in the current directory and bootstrap an " +
			"encrypted repository in the configured blobstore. The passphrase " +
			"is prompted for at the terminal (or sourced via flag/env/keyring).",
		Args:          cobra.NoArgs,
		SilenceUsage:  true,
		SilenceErrors: false,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runInit(cmd, deps, force, flags)
		},
	}
	cmd.Flags().BoolVar(&force, "force", false,
		"overwrite an existing sentra.yaml and re-bootstrap the repo")
	cmd.Flags().StringVar(&flags.bucket, "bucket", "",
		"S3 bucket name (required if no sentra.yaml exists yet)")
	cmd.Flags().StringVar(&flags.region, "region", "",
		"AWS region; e.g. us-west-2 (optional — SDK default chain otherwise)")
	cmd.Flags().StringVar(&flags.profile, "profile", "",
		"AWS shared-config profile (optional)")
	cmd.Flags().StringVar(&flags.endpointURL, "endpoint-url", "",
		"S3 endpoint URL for MinIO/LocalStack (optional; empty for AWS)")
	cmd.Flags().StringVar(&flags.prefix, "prefix", "",
		"S3 key prefix inside the bucket (optional)")
	return cmd
}

// runInit is the body of `sentra init`. Pulled out of the closure so
// it's grep-able and unit-testable independently of cobra.
func runInit(cmd *cobra.Command, deps InitDeps, force bool, flags *initFlags) error {
	// SilenceUsage avoids the noisy "Usage: sentra init ..." dump on
	// every error path; the actual error is what matters.
	cmd.SilenceUsage = true

	// Note whether sentra.yaml exists *before* we apply the --force
	// guard so we can decide whether the bucket flag is required.
	yamlExists := false
	if _, err := os.Stat(configFileName); err == nil {
		yamlExists = true
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("stat %s: %w", configFileName, err)
	}

	// Refuse to clobber an existing sentra.yaml unless the caller
	// passed --force. This guard pairs with repo.Init's refusal to
	// overwrite a non-empty store: both must be satisfied for the
	// init to proceed cleanly.
	if yamlExists && !force {
		return fmt.Errorf("sentra.yaml exists in cwd — refusing to overwrite (use --force)")
	}

	// Build the merged config: Defaults() < sentra.yaml (if it exists,
	// useful with --force) < env overlay (handled by config.Load) <
	// flag values. Calling Load with a missing file returns Defaults()
	// + env, so the same path works fresh-init *and* force-overwrite.
	cfg, err := config.Load(configFileName)
	if err != nil {
		return fmt.Errorf("load config: %w", err)
	}
	applyInitFlags(cfg, flags)

	// Without a bucket, production wiring (newS3Store) refuses to
	// open the store. Catch this at the CLI layer with a clearer
	// message that mentions --bucket and the YAML key.
	if cfg.Repo.S3.Bucket == "" {
		return fmt.Errorf("repo.s3.bucket not set — pass --bucket <name> or edit sentra.yaml first")
	}

	store, err := deps.NewStore(cmd.Context(), cfg)
	if err != nil {
		return fmt.Errorf("open blobstore: %w", err)
	}

	pass, err := deps.Passphrase()
	if err != nil {
		return fmt.Errorf("resolve passphrase: %w", err)
	}
	defer zeroize(pass)

	r, err := repo.Init(cmd.Context(), store, pass)
	if err != nil {
		return fmt.Errorf("init repo: %w", err)
	}
	defer r.Close()

	// Write sentra.yaml AFTER the repo init succeeds — leaving a
	// stale file behind on a failed init would mislead the next run
	// into thinking everything is configured.
	if err := os.WriteFile(configFileName, []byte(renderConfigYAML(cfg)), 0o600); err != nil {
		return fmt.Errorf("write sentra.yaml: %w", err)
	}

	out := deps.Stdout
	if out == nil {
		out = cmd.OutOrStdout()
	}
	fmt.Fprintln(out, ui.Primary.Render("Initialized sentra repository"))
	fmt.Fprintf(out, "  config:   %s\n", configFileName)
	fmt.Fprintf(out, "  repo id:  %s\n", r.Config().ID)
	fmt.Fprintf(out, "  bucket:   %s\n", cfg.Repo.S3.Bucket)
	fmt.Fprintln(out, ui.Subtle.Render("Run `sentra backup <path>` to capture your first snapshot."))
	return nil
}

// applyInitFlags layers the flag values on top of cfg. Empty strings
// mean "leave whatever the YAML/env layer already produced"; a flag
// that's explicitly empty cannot blank out a value from the file.
// In practice that's the right call — the user passed `--bucket=foo`,
// not `--bucket=` — and matches how cobra's StringVar defaults work.
func applyInitFlags(cfg *config.Config, flags *initFlags) {
	if flags.bucket != "" {
		cfg.Repo.S3.Bucket = flags.bucket
	}
	if flags.prefix != "" {
		cfg.Repo.S3.Prefix = flags.prefix
	}
	if flags.region != "" {
		cfg.Repo.S3.Region = flags.region
	}
	if flags.profile != "" {
		cfg.Repo.S3.Profile = flags.profile
	}
	if flags.endpointURL != "" {
		cfg.Repo.S3.EndpointURL = flags.endpointURL
	}
}

// zeroize overwrites b with zeros. Best-effort: the runtime is free to
// move slices around. We still wipe so a heap dump between zeroize and
// GC has at most an all-zero byte slice instead of the live key.
func zeroize(b []byte) {
	for i := range b {
		b[i] = 0
	}
}
