package cli

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"

	"github.com/markgustetic/sentra/internal/blobstore"
	"github.com/markgustetic/sentra/internal/config"
	"github.com/markgustetic/sentra/internal/repo"
	"github.com/markgustetic/sentra/internal/ui"
)

// InitDeps wires the side-effecting pieces of `sentra init` so tests
// can drop in a memory store and a deterministic passphrase. The
// command itself just walks the lifecycle: load config (or defaults),
// open the store, call repo.Init, write sentra.yaml.
type InitDeps struct {
	// NewStore opens the blobstore the new repo will live in.
	// Production wires this to the S3 store; tests pass an in-memory
	// store. The cfg argument is the merged Config from sentra.yaml +
	// env overlay; for `init` on a fresh dir it's typically Defaults().
	NewStore func(ctx context.Context, cfg *config.Config) (blobstore.Store, error)

	// Passphrase returns the passphrase bytes the new repo will be
	// keyed against. Production typically wires this to
	// ui.PromptPassphraseWithConfirm; tests inject a static value so
	// the run is deterministic.
	Passphrase func() ([]byte, error)

	// Stdout receives the success summary. cobra.Command.SetOut also
	// goes here so callers can wire both in one place; if you set
	// SetOut on the returned command directly, that takes precedence.
	Stdout io.Writer
}

// configFileName is the canonical local config file. Always relative
// to the user's working directory — the design doc is explicit that
// init never reaches outside cwd.
const configFileName = "sentra.yaml"

// defaultConfigYAML is the seed contents of sentra.yaml for a fresh
// `sentra init`. Comments tell the user where to plug their values.
// The defaults match config.Defaults so a user who never edits the
// file still gets a runnable config.
const defaultConfigYAML = `# sentra.yaml — repository configuration
# Generated by ` + "`sentra init`" + `. Edit and re-run sentra commands; nothing else
# in this file is required to be present.

repo:
  s3:
    bucket: ""              # required for non-local storage
    prefix: ""              # optional; useful when sharing a bucket
    region: ""              # AWS region; e.g. us-west-2
    profile: ""             # AWS shared-config profile, optional
    endpoint_url: ""        # MinIO/LocalStack support; empty for AWS

agent:
  provider: anthropic
  model: claude-sonnet-4-6
  max_findings_to_llm: 50

backup:
  ignore_file: .sentraignore
  exclude_caches: true

retention:
  keep_last: 10
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6
`

// NewInit returns the cobra command for `sentra init`. The command
// validates the destination, opens the configured store via deps,
// calls repo.Init, and writes sentra.yaml. --force allows clobbering
// an existing sentra.yaml; that's required when the user has changed
// passphrase / bucket / region after the fact and is fine with the
// store being re-bootstrapped (typically against a fresh prefix).
func NewInit(deps InitDeps) *cobra.Command {
	var force bool
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize a sentra repository (writes sentra.yaml + repo config)",
		Long: "Create a sentra.yaml in the current directory and bootstrap an " +
			"encrypted repository in the configured blobstore. The passphrase " +
			"is prompted for at the terminal (or sourced via flag/env/keyring).",
		Args:          cobra.NoArgs,
		SilenceUsage:  true,
		SilenceErrors: false,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runInit(cmd, deps, force)
		},
	}
	cmd.Flags().BoolVar(&force, "force", false,
		"overwrite an existing sentra.yaml and re-bootstrap the repo")
	return cmd
}

// runInit is the body of `sentra init`. Pulled out of the closure so
// it's grep-able and unit-testable independently of cobra.
func runInit(cmd *cobra.Command, deps InitDeps, force bool) error {
	// SilenceUsage avoids the noisy "Usage: sentra init ..." dump on
	// every error path; the actual error is what matters.
	cmd.SilenceUsage = true

	// Refuse to clobber an existing sentra.yaml unless the caller
	// passed --force. This guard pairs with repo.Init's refusal to
	// overwrite a non-empty store: both must be satisfied for the
	// init to proceed cleanly.
	if !force {
		if _, err := os.Stat(configFileName); err == nil {
			return fmt.Errorf("sentra.yaml exists in cwd — refusing to overwrite (use --force)")
		} else if !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("stat %s: %w", configFileName, err)
		}
	}

	// Use defaults for the new repo. Once we land sentra.yaml the
	// user can edit S3 fields and re-open with `sentra backup` etc.
	defaults := config.Defaults()

	store, err := deps.NewStore(cmd.Context(), &defaults)
	if err != nil {
		return fmt.Errorf("open blobstore: %w", err)
	}

	pass, err := deps.Passphrase()
	if err != nil {
		return fmt.Errorf("resolve passphrase: %w", err)
	}
	defer zeroize(pass)

	r, err := repo.Init(cmd.Context(), store, pass)
	if err != nil {
		return fmt.Errorf("init repo: %w", err)
	}
	defer r.Close()

	// Write sentra.yaml AFTER the repo init succeeds — leaving a
	// stale file behind on a failed init would mislead the next run
	// into thinking everything is configured.
	if err := os.WriteFile(configFileName, []byte(defaultConfigYAML), 0o600); err != nil {
		return fmt.Errorf("write sentra.yaml: %w", err)
	}

	out := deps.Stdout
	if out == nil {
		out = cmd.OutOrStdout()
	}
	fmt.Fprintln(out, ui.Primary.Render("Initialized sentra repository"))
	fmt.Fprintf(out, "  config:   %s\n", configFileName)
	fmt.Fprintf(out, "  repo id:  %s\n", r.Config().ID)
	fmt.Fprintln(out, ui.Subtle.Render("Edit sentra.yaml to point at your S3 bucket, then run `sentra backup <path>`."))
	return nil
}

// zeroize overwrites b with zeros. Best-effort: the runtime is free to
// move slices around. We still wipe so a heap dump between zeroize and
// GC has at most an all-zero byte slice instead of the live key.
func zeroize(b []byte) {
	for i := range b {
		b[i] = 0
	}
}
