package walker

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"slices"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"
)

// writeFile is a test helper: create the parent directory if needed
// and write content with a sane mode. Reduces noise across tests.
func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %q: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("write %q: %v", path, err)
	}
}

// collectPaths is a thread-safe collector for parallel walks.
func collectPaths() (func(Entry) error, func() []string) {
	var (
		mu  sync.Mutex
		out []string
	)
	fn := func(e Entry) error {
		mu.Lock()
		out = append(out, e.RelPath)
		mu.Unlock()
		return nil
	}
	get := func() []string {
		mu.Lock()
		defer mu.Unlock()
		c := make([]string, len(out))
		copy(c, out)
		return c
	}
	return fn, get
}

// TestWalk_RespectsIgnore: with a project-level .sentraignore that
// excludes "*.log", the walker should yield .sentraignore itself and
// any non-log file, but not the .log file.
func TestWalk_RespectsIgnore(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "keep.txt"), "k")
	writeFile(t, filepath.Join(root, "skip.log"), "s")
	writeFile(t, filepath.Join(root, ".sentraignore"), "*.log\n")

	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{}, fn); err != nil {
		t.Fatalf("Walk: %v", err)
	}
	got := get()
	slices.Sort(got)
	want := []string{".sentraignore", "keep.txt"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

// TestWalk_HonorsCachedirTag: a directory with a CACHEDIR.TAG that
// starts with the spec signature should be skipped entirely when
// ExcludeCaches is set. We assert no entry under the cache directory
// makes it out, including the tag file itself.
func TestWalk_HonorsCachedirTag(t *testing.T) {
	root := t.TempDir()
	cache := filepath.Join(root, "cache")
	if err := os.Mkdir(cache, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(cache, "CACHEDIR.TAG"),
		"Signature: 8a477f597d28d172789f06886806bc55\nthis directory is a cache")
	writeFile(t, filepath.Join(cache, "junk"), "x")
	writeFile(t, filepath.Join(cache, "nested", "deep"), "y")
	writeFile(t, filepath.Join(root, "real.txt"), "r")

	fn, get := collectPaths()
	err := Walk(context.Background(), root, Options{ExcludeCaches: true}, fn)
	if err != nil {
		t.Fatal(err)
	}
	for _, p := range get() {
		if filepath.Dir(p) == "cache" || len(p) >= 6 && p[:6] == "cache/" {
			t.Errorf("cache should be skipped, but got %q", p)
		}
	}
}

// TestWalk_HonorsCachedirTagOnlyWhenSet: without ExcludeCaches the
// cache dir contents should be returned. This pins the opt-in
// semantics — we don't want a default that silently drops files.
func TestWalk_HonorsCachedirTagOnlyWhenSet(t *testing.T) {
	root := t.TempDir()
	cache := filepath.Join(root, "cache")
	if err := os.Mkdir(cache, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(cache, "CACHEDIR.TAG"),
		"Signature: 8a477f597d28d172789f06886806bc55")
	writeFile(t, filepath.Join(cache, "junk"), "x")

	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{}, fn); err != nil {
		t.Fatal(err)
	}
	got := get()
	slices.Sort(got)
	want := []string{"cache/CACHEDIR.TAG", "cache/junk"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

// TestWalk_CachedirTagWrongSignature: a CACHEDIR.TAG file whose
// signature doesn't match the spec must NOT cause the directory to
// be skipped. This protects against accidentally hiding a directory
// that happens to contain a file by that name.
func TestWalk_CachedirTagWrongSignature(t *testing.T) {
	root := t.TempDir()
	cache := filepath.Join(root, "cache")
	if err := os.Mkdir(cache, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(cache, "CACHEDIR.TAG"), "this is not a real cachedir tag")
	writeFile(t, filepath.Join(cache, "junk"), "x")

	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{ExcludeCaches: true}, fn); err != nil {
		t.Fatal(err)
	}
	got := get()
	slices.Sort(got)
	want := []string{"cache/CACHEDIR.TAG", "cache/junk"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

// TestWalk_CachedirTagSignatureWithTrailingComment: per the
// CACHEDIR.TAG spec, the signature only needs to be a prefix of the
// first line — tools may append trailing content (e.g. comments).
// The walker must accept a tag like "Signature: ... # made by foo"
// and skip the directory.
func TestWalk_CachedirTagSignatureWithTrailingComment(t *testing.T) {
	root := t.TempDir()
	cache := filepath.Join(root, "cache")
	if err := os.Mkdir(cache, 0o755); err != nil {
		t.Fatal(err)
	}
	tag := "Signature: 8a477f597d28d172789f06886806bc55 # generated by foo"
	writeFile(t, filepath.Join(cache, "CACHEDIR.TAG"), tag)
	writeFile(t, filepath.Join(cache, "junk"), "x")
	writeFile(t, filepath.Join(root, "real.txt"), "r")

	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{ExcludeCaches: true}, fn); err != nil {
		t.Fatal(err)
	}
	got := get()
	for _, p := range got {
		if strings.HasPrefix(p, "cache/") {
			t.Errorf("cache should be skipped, got %v in %v", p, got)
		}
	}
	if len(got) != 1 || got[0] != "real.txt" {
		t.Errorf("got %v, want [real.txt]", got)
	}
}

// TestWalk_DoesNotFollowSymlinks: a symlink (to a file or directory)
// is not a regular file under filepath.WalkDir's lstat semantics, so
// the walker should ignore it and emit no entry. Following symlinks
// is a v2 question; for now we want predictable, non-cyclic walks.
func TestWalk_DoesNotFollowSymlinks(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "real.txt"), "r")

	target := filepath.Join(root, "real.txt")
	link := filepath.Join(root, "link.txt")
	if err := os.Symlink(target, link); err != nil {
		t.Skipf("symlink unsupported on this filesystem: %v", err)
	}

	// Also add a symlinked directory to make sure we don't recurse
	// into the target.
	otherDir := t.TempDir()
	writeFile(t, filepath.Join(otherDir, "outside.txt"), "o")
	dirLink := filepath.Join(root, "dirlink")
	if err := os.Symlink(otherDir, dirLink); err != nil {
		t.Skipf("symlink unsupported on this filesystem: %v", err)
	}

	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{}, fn); err != nil {
		t.Fatal(err)
	}
	got := get()
	slices.Sort(got)
	want := []string{"real.txt"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v (symlinks must be skipped)", got, want)
	}
}

// TestWalk_IncludeNonRegular_EmitsSymlinksAndDirs: with the opt-in
// set, the walker emits directory entries (so empty dirs and dir
// modes survive a snapshot) and symlink entries carrying their target
// — without following either.
func TestWalk_IncludeNonRegular_EmitsSymlinksAndDirs(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "sub", "a.txt"), "a")
	if err := os.Mkdir(filepath.Join(root, "emptyd"), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink("sub/a.txt", filepath.Join(root, "ln")); err != nil {
		t.Skipf("symlink unsupported on this filesystem: %v", err)
	}

	var mu sync.Mutex
	byPath := map[string]Entry{}
	err := Walk(context.Background(), root, Options{IncludeNonRegular: true}, func(e Entry) error {
		mu.Lock()
		byPath[e.RelPath] = e
		mu.Unlock()
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}

	if e, ok := byPath["emptyd"]; !ok || e.Kind != KindDir {
		t.Errorf("empty dir not emitted as KindDir: %+v", byPath["emptyd"])
	} else if e.Mode.Perm() != 0o700 {
		t.Errorf("dir mode: got %v, want 0700", e.Mode.Perm())
	}
	if e, ok := byPath["sub"]; !ok || e.Kind != KindDir {
		t.Errorf("non-empty dir not emitted as KindDir: %+v", byPath["sub"])
	}
	if e, ok := byPath["ln"]; !ok || e.Kind != KindSymlink {
		t.Errorf("symlink not emitted as KindSymlink: %+v", byPath["ln"])
	} else if e.LinkTarget != "sub/a.txt" {
		t.Errorf("symlink target: got %q, want %q", e.LinkTarget, "sub/a.txt")
	}
	if e, ok := byPath["sub/a.txt"]; !ok || e.Kind != KindFile {
		t.Errorf("regular file must stay KindFile: %+v", byPath["sub/a.txt"])
	}
	if _, ok := byPath["."]; ok {
		t.Error("the walk root itself must not be emitted")
	}
}

// TestWalk_DefaultOmitsNonRegular pins the compatibility rule: without
// the opt-in, callers see exactly what they always saw — regular files
// only — so plan/heuristics flows are unaffected by the new kinds.
func TestWalk_DefaultOmitsNonRegular(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "sub", "a.txt"), "a")
	if err := os.Mkdir(filepath.Join(root, "emptyd"), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink("sub/a.txt", filepath.Join(root, "ln")); err != nil {
		t.Skipf("symlink unsupported on this filesystem: %v", err)
	}
	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{}, fn); err != nil {
		t.Fatal(err)
	}
	got := get()
	slices.Sort(got)
	want := []string{"sub/a.txt"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("default walk emitted %v, want %v", got, want)
	}
}

// TestWalk_IncludeNonRegular_HonorsIgnore: ignore patterns apply to
// symlinks and directories the same way they apply to files.
func TestWalk_IncludeNonRegular_HonorsIgnore(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, ".sentraignore"), "ln\nskipd/\n")
	writeFile(t, filepath.Join(root, "keep.txt"), "k")
	if err := os.Mkdir(filepath.Join(root, "skipd"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink("keep.txt", filepath.Join(root, "ln")); err != nil {
		t.Skipf("symlink unsupported on this filesystem: %v", err)
	}
	var mu sync.Mutex
	byPath := map[string]Entry{}
	err := Walk(context.Background(), root, Options{IncludeNonRegular: true}, func(e Entry) error {
		mu.Lock()
		byPath[e.RelPath] = e
		mu.Unlock()
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := byPath["ln"]; ok {
		t.Error("ignored symlink must not be emitted")
	}
	if _, ok := byPath["skipd"]; ok {
		t.Error("ignored dir must not be emitted")
	}
}

// TestWalk_RespectsContextCancel: cancelling the context mid-walk
// should surface context.Canceled. We rig fn to cancel as soon as it
// sees an entry, then assert the returned error.
func TestWalk_RespectsContextCancel(t *testing.T) {
	root := t.TempDir()
	for i := 0; i < 200; i++ {
		writeFile(t, filepath.Join(root, fmt.Sprintf("f-%d.txt", i)), "x")
	}
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	var seen atomic.Int64
	fn := func(_ Entry) error {
		if seen.Add(1) == 1 {
			cancel()
		}
		// Best-effort: return ctx error so the cancel races to
		// surface from either the producer or fn.
		return ctx.Err()
	}

	err := Walk(ctx, root, Options{}, fn)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("Walk error = %v, want context.Canceled", err)
	}
}

// TestWalk_FnErrorPropagates: the first non-nil error from fn must be
// returned by Walk, and the walk must stop (best-effort). We don't
// assert on exact fn-call counts because workers may have already
// dequeued additional entries.
func TestWalk_FnErrorPropagates(t *testing.T) {
	root := t.TempDir()
	for i := 0; i < 50; i++ {
		writeFile(t, filepath.Join(root, fmt.Sprintf("f-%d.txt", i)), "x")
	}

	sentinel := errors.New("intentional fn error")
	fn := func(_ Entry) error { return sentinel }

	err := Walk(context.Background(), root, Options{}, fn)
	if !errors.Is(err, sentinel) {
		t.Fatalf("Walk error = %v, want %v", err, sentinel)
	}
}

// TestWalk_NestedDirs: deep tree with multiple levels yields all the
// expected files. Order is unspecified (concurrent walk), so sort
// before comparing.
func TestWalk_NestedDirs(t *testing.T) {
	root := t.TempDir()
	files := []string{
		"a.txt",
		"dir1/b.txt",
		"dir1/dir2/c.txt",
		"dir1/dir2/dir3/d.txt",
		"dir1/dir2/dir3/e.txt",
		"sibling/f.txt",
	}
	for _, f := range files {
		writeFile(t, filepath.Join(root, f), "x")
	}

	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{}, fn); err != nil {
		t.Fatal(err)
	}
	got := get()
	slices.Sort(got)
	slices.Sort(files)
	if !reflect.DeepEqual(got, files) {
		t.Errorf("got %v, want %v", got, files)
	}
}

// TestWalk_DefaultIgnoreFileName: when Options.IgnoreFile is empty,
// the walker should default to ".sentraignore". Without this default
// callers would have to set IgnoreFile every time.
func TestWalk_DefaultIgnoreFileName(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "keep.txt"), "k")
	writeFile(t, filepath.Join(root, "drop.tmp"), "d")
	writeFile(t, filepath.Join(root, ".sentraignore"), "*.tmp\n")

	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{IgnoreFile: ""}, fn); err != nil {
		t.Fatal(err)
	}
	got := get()
	slices.Sort(got)
	want := []string{".sentraignore", "keep.txt"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

// TestWalk_CustomIgnoreFile: a non-default ignore filename should be
// honored. Useful for callers who want to drive the walker from a
// different config file.
func TestWalk_CustomIgnoreFile(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "keep.txt"), "k")
	writeFile(t, filepath.Join(root, "drop.tmp"), "d")
	writeFile(t, filepath.Join(root, ".myignore"), "*.tmp\n")

	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{IgnoreFile: ".myignore"}, fn); err != nil {
		t.Fatal(err)
	}
	got := get()
	slices.Sort(got)
	want := []string{".myignore", "keep.txt"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

// TestWalk_ConcurrencyZeroDefaults: Options.Concurrency == 0 must not
// hang or panic. We don't assert on a specific worker count — just
// that the walk completes.
func TestWalk_ConcurrencyZeroDefaults(t *testing.T) {
	root := t.TempDir()
	for i := 0; i < 20; i++ {
		writeFile(t, filepath.Join(root, fmt.Sprintf("f-%d.txt", i)), "x")
	}

	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{Concurrency: 0}, fn); err != nil {
		t.Fatal(err)
	}
	if len(get()) != 20 {
		t.Errorf("got %d entries, want 20", len(get()))
	}
}

// TestWalk_ConcurrencyExplicit: passing a small explicit count works.
// Combined with -race this exercises the worker pool's safety.
func TestWalk_ConcurrencyExplicit(t *testing.T) {
	root := t.TempDir()
	for i := 0; i < 100; i++ {
		writeFile(t, filepath.Join(root, fmt.Sprintf("f-%d.txt", i)), "x")
	}

	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{Concurrency: 4}, fn); err != nil {
		t.Fatal(err)
	}
	if len(get()) != 100 {
		t.Errorf("got %d entries, want 100", len(get()))
	}
}

// TestWalk_EntryFields: verify that Entry is populated with the
// correct AbsPath, RelPath, Size, Mode, and a non-zero MTime. Without
// this, downstream stages that key off mtime for change detection
// will silently see zero values.
func TestWalk_EntryFields(t *testing.T) {
	root := t.TempDir()
	rel := "subdir/hello.txt"
	abs := filepath.Join(root, rel)
	writeFile(t, abs, "hello, world")

	var got Entry
	var mu sync.Mutex
	fn := func(e Entry) error {
		mu.Lock()
		got = e
		mu.Unlock()
		return nil
	}
	if err := Walk(context.Background(), root, Options{}, fn); err != nil {
		t.Fatal(err)
	}
	if got.RelPath != "subdir/hello.txt" {
		t.Errorf("RelPath=%q, want %q", got.RelPath, "subdir/hello.txt")
	}
	if got.AbsPath != abs {
		t.Errorf("AbsPath=%q, want %q", got.AbsPath, abs)
	}
	if got.Size != int64(len("hello, world")) {
		t.Errorf("Size=%d, want %d", got.Size, len("hello, world"))
	}
	if got.Mode.IsRegular() == false {
		t.Errorf("Mode=%v, want regular file", got.Mode)
	}
	if got.MTime.IsZero() {
		t.Error("MTime is zero")
	}
	if time.Since(got.MTime) > time.Hour {
		t.Errorf("MTime=%v looks too old for a file we just created", got.MTime)
	}
}

// TestWalk_ConcurrencyDefaultsToGOMAXPROCS smokes the GOMAXPROCS
// branch by checking that Concurrency==0 produces multiple goroutines
// when GOMAXPROCS > 1. We can't directly observe the worker count, so
// we settle for "the walk completes in a reasonable time" — really
// just a regression guard.
func TestWalk_ConcurrencyDefaultsToGOMAXPROCS(t *testing.T) {
	if runtime.GOMAXPROCS(0) < 2 {
		t.Skip("needs GOMAXPROCS >= 2 to be meaningful")
	}
	root := t.TempDir()
	for i := 0; i < 50; i++ {
		writeFile(t, filepath.Join(root, fmt.Sprintf("f-%d.txt", i)), "x")
	}
	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{Concurrency: 0}, fn); err != nil {
		t.Fatal(err)
	}
	if len(get()) != 50 {
		t.Errorf("got %d, want 50", len(get()))
	}
}

// TestWalk_RootDoesNotExist surfaces an I/O error from the walk
// itself, not a silent zero-result success.
func TestWalk_RootDoesNotExist(t *testing.T) {
	bogus := filepath.Join(t.TempDir(), "no-such-dir")
	err := Walk(context.Background(), bogus, Options{}, func(Entry) error { return nil })
	if err == nil {
		t.Fatal("expected error for non-existent root, got nil")
	}
}

// TestWalk_CachedirTagNeverSkipsRoot pins the rule that the root is
// exempt from the cache-tag short-circuit. The operator named that
// directory on purpose; treating its own CACHEDIR.TAG as "skip me"
// silently produced an empty backup with exit 0. A tagged *child*
// directory must still be skipped, so the guard is root-only and not
// a regression of the ExcludeCaches feature.
func TestWalk_CachedirTagNeverSkipsRoot(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "CACHEDIR.TAG"),
		"Signature: 8a477f597d28d172789f06886806bc55\n")
	writeFile(t, filepath.Join(root, "real.txt"), "r")
	writeFile(t, filepath.Join(root, "cache", "CACHEDIR.TAG"),
		"Signature: 8a477f597d28d172789f06886806bc55\n")
	writeFile(t, filepath.Join(root, "cache", "junk"), "x")

	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{ExcludeCaches: true}, fn); err != nil {
		t.Fatal(err)
	}
	got := get()
	slices.Sort(got)
	want := []string{"CACHEDIR.TAG", "real.txt"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v (root must be walked; tagged child skipped)", got, want)
	}
}

// TestWalk_VanishedFileIsSkipped pins the rule that a regular file
// which disappears between the producer's readdir and the worker's
// Lstat is dropped, not fatal: a live tree (build outputs, editor
// swap files, browser caches) does this constantly, and one such
// race must not abort a whole backup. Determinism without a hook:
// WalkDir reads a directory's full listing before its first
// callback, and with Concurrency 1 the single worker Lstats entries
// strictly in order, so deleting "b" from inside fn("a") guarantees
// "b"'s Lstat runs after the delete.
func TestWalk_VanishedFileIsSkipped(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "a"), "a")
	writeFile(t, filepath.Join(root, "b"), "b")

	var (
		mu  sync.Mutex
		got []string
	)
	fn := func(e Entry) error {
		mu.Lock()
		defer mu.Unlock()
		got = append(got, e.RelPath)
		if e.RelPath == "a" {
			if err := os.Remove(filepath.Join(root, "b")); err != nil {
				return err
			}
		}
		return nil
	}
	if err := Walk(context.Background(), root, Options{Concurrency: 1}, fn); err != nil {
		t.Fatalf("Walk: vanished file must be skipped, got %v", err)
	}
	if want := []string{"a"}; !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got, want)
	}
}

// skipUnlessChmodDenies guards the EPERM tests: root ignores mode
// bits, so a chmod-000 directory is still readable and the walk
// would (correctly) not skip anything.
func skipUnlessChmodDenies(t *testing.T) {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("chmod permission denial is not modeled on windows")
	}
	if os.Geteuid() == 0 {
		t.Skip("running as root; chmod cannot deny access")
	}
}

// mkdirLocked creates dir with the given mode and restores 0o755 at
// cleanup so t.TempDir can remove it.
func mkdirLocked(t *testing.T, dir string, mode os.FileMode) {
	t.Helper()
	if err := os.Chmod(dir, mode); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(dir, 0o755) })
}

// TestWalk_UnreadableSubdirIsSkippedAndReported pins the rule for a
// subdirectory whose ReadDir is denied (TCC-protected dirs under
// ~/Library on macOS are the real-world case): the subtree is
// skipped, the walk continues, and OnSkip is told exactly which path
// and why so a surface can show it. Everything outside the locked
// directory must still be emitted — the point is that one protected
// folder does not cost the operator the whole backup.
func TestWalk_UnreadableSubdirIsSkippedAndReported(t *testing.T) {
	skipUnlessChmodDenies(t)
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "ok.txt"), "ok")
	writeFile(t, filepath.Join(root, "after", "z.txt"), "z")
	locked := filepath.Join(root, "locked")
	writeFile(t, filepath.Join(locked, "secret.txt"), "s")
	mkdirLocked(t, locked, 0)

	var (
		mu    sync.Mutex
		skips []string
		errs  []error
	)
	fn, get := collectPaths()
	opts := Options{
		IncludeNonRegular: true,
		OnSkip: func(path string, err error) {
			mu.Lock()
			defer mu.Unlock()
			skips = append(skips, path)
			errs = append(errs, err)
		},
	}
	if err := Walk(context.Background(), root, opts, fn); err != nil {
		t.Fatalf("Walk: unreadable subdir must be skipped, got %v", err)
	}

	got := get()
	slices.Sort(got)
	// "locked" itself is emitted as a KindDir: its metadata was
	// readable and the entry is honest; only its contents are gone.
	want := []string{"after", "after/z.txt", "locked", "ok.txt"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("emitted %v, want %v", got, want)
	}
	if want := []string{locked}; !reflect.DeepEqual(skips, want) {
		t.Fatalf("OnSkip paths %v, want %v", skips, want)
	}
	if !errors.Is(errs[0], fs.ErrPermission) {
		t.Errorf("OnSkip err %v, want fs.ErrPermission", errs[0])
	}
}

// TestWalk_UnreadableSubdirWithoutOnSkip: nil OnSkip means silent,
// not a nil-func panic and not a fatal walk.
func TestWalk_UnreadableSubdirWithoutOnSkip(t *testing.T) {
	skipUnlessChmodDenies(t)
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "ok.txt"), "ok")
	locked := filepath.Join(root, "locked")
	writeFile(t, filepath.Join(locked, "secret.txt"), "s")
	mkdirLocked(t, locked, 0)

	fn, get := collectPaths()
	if err := Walk(context.Background(), root, Options{}, fn); err != nil {
		t.Fatalf("Walk: %v", err)
	}
	if want := []string{"ok.txt"}; !reflect.DeepEqual(get(), want) {
		t.Errorf("got %v, want %v", get(), want)
	}
}

// TestWalk_UnreadableRootIsFatal: the skip rule is for subtrees only.
// A root whose listing is denied has nothing to fall back to, and an
// empty successful walk would be the silent-empty-backup bug in a new
// costume. Mode 0o300 keeps the root searchable (so the ignore-file
// lookup gets a clean not-exist) while denying ReadDir, which is the
// exact failure the producer callback sees.
func TestWalk_UnreadableRootIsFatal(t *testing.T) {
	skipUnlessChmodDenies(t)
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "ok.txt"), "ok")
	mkdirLocked(t, root, 0o300)

	skipped := false
	opts := Options{OnSkip: func(string, error) { skipped = true }}
	err := Walk(context.Background(), root, opts, func(Entry) error { return nil })
	if !errors.Is(err, fs.ErrPermission) {
		t.Fatalf("Walk err = %v, want fs.ErrPermission", err)
	}
	if skipped {
		t.Error("OnSkip fired for the root; the root must be fatal, not skipped")
	}
}
