package config

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// defaultAgentProvider / defaultAgentModel are the documented agent
// defaults written when the resolved config leaves them unset. Defaults()
// deliberately does not seed Provider/Model, so a render must fall back to
// these rather than emit an empty value.
const (
	defaultAgentProvider = "anthropic"
	defaultAgentModel    = "claude-sonnet-4-6"
)

// Render produces the on-disk sentra.yaml body that init, setup, policy
// add/remove, and passwd-forget write. We render from the resolved Config
// (defaults + yaml + env overlay + flags/prompts) so the file faithfully
// reflects what the user actually configured.
//
// The body is hand-shaped rather than yaml.Marshal'd so we can keep the
// inline comments that explain each field — the file is a teaching
// artifact, not just a serialization. No secret material (passphrase,
// wrapped keys, salts) is ever a Config field, so this can never leak one.
func Render(cfg *Config) []byte {
	// Render the agent provider/model from the resolved config so a
	// user's customized values round-trip through any config rewrite.
	// Falling back to the documented defaults only when unset preserves a
	// complete file for fresh configs without clobbering a non-default
	// choice.
	agentProvider := cfg.Agent.Provider
	if agentProvider == "" {
		agentProvider = defaultAgentProvider
	}
	agentModel := cfg.Agent.Model
	if agentModel == "" {
		agentModel = defaultAgentModel
	}
	return []byte(fmt.Sprintf(`# sentra.yaml — repository configuration
# Generated by Sentra. Edit and re-run sentra commands; nothing else
# in this file is required to be present.

repo:
  s3:
    bucket: %q              # required for non-local storage
    prefix: %q              # optional; useful when sharing a bucket
    region: %q              # AWS region; e.g. us-west-2
    profile: %q             # AWS shared-config profile, optional
    endpoint_url: %q        # MinIO/LocalStack support; empty for AWS
    storage_class: %q       # S3 storage class for new blobs; empty = bucket default

agent:
  provider: %q
  model: %q
  max_findings_to_llm: %d

backup:
  ignore_file: %q
  exclude_caches: %t
  concurrency: %d
  max_upload_rate: %d

retention:
  keep_last: %d
  keep_daily: %d
  keep_weekly: %d
  keep_monthly: %d

passphrase:
  use_keyring: %t

ui:
  hide_splash: %t         # true skips the welcome splash at launch
%s`,
		cfg.Repo.S3.Bucket,
		cfg.Repo.S3.Prefix,
		cfg.Repo.S3.Region,
		cfg.Repo.S3.Profile,
		cfg.Repo.S3.EndpointURL,
		cfg.Repo.S3.StorageClass,
		agentProvider,
		agentModel,
		cfg.Agent.MaxFindingsToLLM,
		cfg.Backup.IgnoreFile,
		cfg.Backup.ExcludeCaches,
		cfg.Backup.Concurrency,
		cfg.Backup.MaxUploadRate,
		cfg.Retention.KeepLast,
		cfg.Retention.KeepDaily,
		cfg.Retention.KeepWeekly,
		cfg.Retention.KeepMonthly,
		cfg.Passphrase.UseKeyring,
		cfg.UI.HideSplash,
		renderPoliciesYAML(cfg.Policies),
	))
}

func renderPoliciesYAML(policies map[string]PolicyConfig) string {
	if len(policies) == 0 {
		return ""
	}
	names := make([]string, 0, len(policies))
	for name := range policies {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("\npolicies:\n")
	for _, name := range names {
		p := policies[name]
		// The name is the only map key in the file that comes from the user,
		// and ValidateName admits scalar-looking names ("07", "1e3", "null").
		// Bare, yaml.v3 re-types those on the next Load ("07" -> "7", "null"
		// -> nil), so the policy the operator just added can't be found by
		// the name they gave it and the timer installed for it fails on every
		// fire. Quoting the key pins it as a string, as every value already is.
		fmt.Fprintf(&b, "  %q:\n", name)
		writeYAMLStringList(&b, "    paths", p.Paths)
		writeYAMLStringList(&b, "    tags", p.Tags)
		fmt.Fprintln(&b, "    schedule:")
		fmt.Fprintf(&b, "      cadence: %q\n", p.Schedule.Cadence)
		if p.Schedule.At != "" {
			fmt.Fprintf(&b, "      at: %q\n", p.Schedule.At)
		}
		if p.Schedule.Weekday != "" {
			fmt.Fprintf(&b, "      weekday: %q\n", p.Schedule.Weekday)
		}
		fmt.Fprintln(&b, "    after_backup:")
		fmt.Fprintf(&b, "      check: %t\n", p.AfterBackup.Check)
		fmt.Fprintf(&b, "      prune: %q\n", p.AfterBackup.Prune)
		if p.Hooks != (PolicyHooks{}) {
			fmt.Fprintln(&b, "    hooks:")
			if p.Hooks.Before != "" {
				fmt.Fprintf(&b, "      before: %q\n", p.Hooks.Before)
			}
			if p.Hooks.After != "" {
				fmt.Fprintf(&b, "      after: %q\n", p.Hooks.After)
			}
			if p.Hooks.OnFailure != "" {
				fmt.Fprintf(&b, "      on_failure: %q\n", p.Hooks.OnFailure)
			}
			if p.Hooks.OnFailureWebhookEnv != "" {
				fmt.Fprintf(&b, "      on_failure_webhook_env: %q\n", p.Hooks.OnFailureWebhookEnv)
			}
		}
	}
	return b.String()
}

func writeYAMLStringList(b *strings.Builder, key string, values []string) {
	if len(values) == 0 {
		fmt.Fprintf(b, "%s: []\n", key)
		return
	}
	fmt.Fprintf(b, "%s:\n", key)
	for _, value := range values {
		fmt.Fprintf(b, "      - %q\n", value)
	}
}

// Write renders cfg and writes it to path with 0o600 perms. The file
// names the bucket/region/profile but never a secret, yet 0o600 keeps it
// out of other users' reach as a matter of policy hygiene.
//
// Write creates path's parent directory (0o700) when missing — the user-level
// config location may not exist on a fresh machine.
//
// Write authors the *whole* file from the Config it is handed, so it is only
// correct when the caller means to materialize a resolved config: `init`
// (Defaults < yaml < env < flags, and it must record the bucket it just
// initialized) and `setup` (the wizard prompts for these values and shows them
// on the review screen before provisioning against them). Both would otherwise
// write `bucket: ""` after acting on an env-supplied bucket.
//
// To change one field of an existing file, use Update. Passing a Config from
// Load to Write silently persists that process's SENTRA_* overrides.
//
// The replacement is atomic (temp file + rename, see writeAtomic): a crash
// mid-write must never leave a truncated sentra.yaml, because an empty file
// still counts as configured (ConfigExists) yet loads as bucket "" — the next
// launch lands on the connect gate with the bucket, profile and every policy
// gone, and nothing on screen says why.
func Write(path string, cfg *Config) error {
	// The user-level fallback path (~/.config/sentra/sentra.yaml) may be
	// the first thing ever written there; create the directory rather
	// than failing on a fresh machine. 0o700 matches the file's 0o600.
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create config dir %s: %w", filepath.Dir(path), err)
	}
	body := Render(cfg)
	return writeAtomic(path, func(w io.Writer) error {
		_, err := w.Write(body)
		return err
	})
}

// writeAtomic streams write's output into a 0o600 temp file beside path,
// fsyncs it, and renames it over path, so readers only ever observe the old
// file or the complete new one. Every failure leg removes the temp file: a
// stray `.sentra-*.tmp` beside the config would otherwise outlive the crash
// it was meant to protect against. The temp file lives in the target's
// directory because rename is atomic only within one filesystem. Same shape
// as the credentials-file writer in internal/setup.
//
// write is a callback rather than a finished []byte so a test can fail
// midway through the write and prove the previous file survives; Write
// itself just hands over the completed render.
//
// A symlinked path is written through, not replaced. Operators keep
// sentra.yaml in a dotfiles repo behind a symlink (stow, chezmoi, `ln -s`),
// and renaming the temp file over the link would swap the link for a
// regular file — severing the dotfiles on every settings toggle, policy add
// or passwd forget, which the plain os.WriteFile this replaced never did.
// So when path is a symlink it is resolved with EvalSymlinks and the
// resolved file is what gets staged beside and renamed over. A dangling
// link is an error rather than a fresh file: creating a regular file at the
// link's path is the same severing, and inventing the target's directory
// writes where nobody asked. A path that does not exist at all stays as
// given, so a fresh config lands exactly where the operator named it.
func writeAtomic(path string, write func(w io.Writer) error) error {
	target, err := resolveWriteTarget(path)
	if err != nil {
		return err
	}
	dir := filepath.Dir(target)
	tmp, err := os.CreateTemp(dir, ".sentra-*.tmp")
	if err != nil {
		return fmt.Errorf("create temp config file in %s: %w", dir, err)
	}
	tmpPath := tmp.Name()
	fail := func(step string, err error) error {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("%s %s: %w", step, path, err)
	}
	if err := write(tmp); err != nil {
		return fail("write", err)
	}
	// CreateTemp already opens 0o600 and a umask can only clear bits from
	// that, so this is belt and braces: restore 0o600 explicitly in case a
	// platform's CreateTemp decides otherwise; the file names the bucket
	// and region.
	if err := tmp.Chmod(0o600); err != nil {
		return fail("chmod", err)
	}
	// Sync before rename: on a power loss, an unsynced rename can land the
	// new name on zero-length content — exactly the empty file this exists
	// to prevent.
	if err := tmp.Sync(); err != nil {
		return fail("sync", err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("close %s: %w", path, err)
	}
	if err := os.Rename(tmpPath, target); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("replace %s: %w", path, err)
	}
	return nil
}

// resolveWriteTarget returns the file writeAtomic should stage beside and
// rename over: path itself unless path is a symlink, in which case the
// fully resolved target. See writeAtomic for why a link is written through
// and why a dangling one fails instead of being overwritten.
func resolveWriteTarget(path string) (string, error) {
	fi, err := os.Lstat(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return path, nil
		}
		return "", fmt.Errorf("stat %s: %w", path, err)
	}
	if fi.Mode()&os.ModeSymlink == 0 {
		return path, nil
	}
	target, err := filepath.EvalSymlinks(path)
	if err != nil {
		return "", fmt.Errorf("resolve symlink %s: %w", path, err)
	}
	return target, nil
}

// Update applies mutate to the config as it exists on disk and writes the
// result back to path. It is the safe way to change one field of sentra.yaml.
//
// The base is loadOnDisk, not Load. Load overlays SENTRA_* env vars, and
// rendering that resolved Config back out would bake a transient override into
// the file permanently: flipping the cosmetic splash toggle under
// `SENTRA_REPO__S3__BUCKET=scratch` used to rewrite the operator's real bucket.
// Everything mutate does not touch round-trips back exactly as the file had it.
//
// mutate sees Defaults() + whatever the file said, so a partial sentra.yaml
// still renders complete. Returning an error from mutate aborts before any
// write — the file is left untouched — which lets callers fold validation
// (duplicate policy names, unknown keys) into the same critical section.
func Update(path string, mutate func(*Config) error) error {
	cfg, err := loadOnDisk(path)
	if err != nil {
		return err
	}
	if err := mutate(cfg); err != nil {
		return err
	}
	return Write(path, cfg)
}
