package config

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// defaultAgentProvider / defaultAgentModel are the documented agent
// defaults written when the resolved config leaves them unset. Defaults()
// deliberately does not seed Provider/Model, so a render must fall back to
// these rather than emit an empty value.
const (
	defaultAgentProvider = "anthropic"
	defaultAgentModel    = "claude-sonnet-4-6"
)

// Render produces the on-disk sentra.yaml body that init, setup, policy
// add/remove, and passwd-forget write. We render from the resolved Config
// (defaults + yaml + env overlay + flags/prompts) so the file faithfully
// reflects what the user actually configured.
//
// The body is hand-shaped rather than yaml.Marshal'd so we can keep the
// inline comments that explain each field — the file is a teaching
// artifact, not just a serialization. No secret material (passphrase,
// wrapped keys, salts) is ever a Config field, so this can never leak one.
func Render(cfg *Config) []byte {
	// Render the agent provider/model from the resolved config so a
	// user's customized values round-trip through any config rewrite.
	// Falling back to the documented defaults only when unset preserves a
	// complete file for fresh configs without clobbering a non-default
	// choice.
	agentProvider := cfg.Agent.Provider
	if agentProvider == "" {
		agentProvider = defaultAgentProvider
	}
	agentModel := cfg.Agent.Model
	if agentModel == "" {
		agentModel = defaultAgentModel
	}
	return []byte(fmt.Sprintf(`# sentra.yaml — repository configuration
# Generated by Sentra. Edit and re-run sentra commands; nothing else
# in this file is required to be present.

repo:
  s3:
    bucket: %q              # required for non-local storage
    prefix: %q              # optional; useful when sharing a bucket
    region: %q              # AWS region; e.g. us-west-2
    profile: %q             # AWS shared-config profile, optional
    endpoint_url: %q        # MinIO/LocalStack support; empty for AWS

agent:
  provider: %q
  model: %q
  max_findings_to_llm: %d

backup:
  ignore_file: %q
  exclude_caches: %t

retention:
  keep_last: %d
  keep_daily: %d
  keep_weekly: %d
  keep_monthly: %d

passphrase:
  use_keyring: %t

ui:
  hide_splash: %t         # true skips the welcome splash at launch
%s`,
		cfg.Repo.S3.Bucket,
		cfg.Repo.S3.Prefix,
		cfg.Repo.S3.Region,
		cfg.Repo.S3.Profile,
		cfg.Repo.S3.EndpointURL,
		agentProvider,
		agentModel,
		cfg.Agent.MaxFindingsToLLM,
		cfg.Backup.IgnoreFile,
		cfg.Backup.ExcludeCaches,
		cfg.Retention.KeepLast,
		cfg.Retention.KeepDaily,
		cfg.Retention.KeepWeekly,
		cfg.Retention.KeepMonthly,
		cfg.Passphrase.UseKeyring,
		cfg.UI.HideSplash,
		renderPoliciesYAML(cfg.Policies),
	))
}

func renderPoliciesYAML(policies map[string]PolicyConfig) string {
	if len(policies) == 0 {
		return ""
	}
	names := make([]string, 0, len(policies))
	for name := range policies {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("\npolicies:\n")
	for _, name := range names {
		p := policies[name]
		fmt.Fprintf(&b, "  %s:\n", name)
		writeYAMLStringList(&b, "    paths", p.Paths)
		writeYAMLStringList(&b, "    tags", p.Tags)
		fmt.Fprintln(&b, "    schedule:")
		fmt.Fprintf(&b, "      cadence: %q\n", p.Schedule.Cadence)
		if p.Schedule.At != "" {
			fmt.Fprintf(&b, "      at: %q\n", p.Schedule.At)
		}
		if p.Schedule.Weekday != "" {
			fmt.Fprintf(&b, "      weekday: %q\n", p.Schedule.Weekday)
		}
		fmt.Fprintln(&b, "    after_backup:")
		fmt.Fprintf(&b, "      check: %t\n", p.AfterBackup.Check)
		fmt.Fprintf(&b, "      prune: %q\n", p.AfterBackup.Prune)
	}
	return b.String()
}

func writeYAMLStringList(b *strings.Builder, key string, values []string) {
	if len(values) == 0 {
		fmt.Fprintf(b, "%s: []\n", key)
		return
	}
	fmt.Fprintf(b, "%s:\n", key)
	for _, value := range values {
		fmt.Fprintf(b, "      - %q\n", value)
	}
}

// Write renders cfg and writes it to path with 0o600 perms. The file
// names the bucket/region/profile but never a secret, yet 0o600 keeps it
// out of other users' reach as a matter of policy hygiene.
func Write(path string, cfg *Config) error {
	if err := os.WriteFile(path, Render(cfg), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
